name = "Dmeh"
license = "MIT"
licenselink = "https://github.com/heimann/dmeh-layout/blob/master/LICENSE"
description = "Hugo Theme for my personal website."
homepage = "http://dmeh.net/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "David Heimann"
  homepage = "dmeh.net"

